version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ${BACKEND_CONTAINER_NAME}

    ports:
      - "${APP_PORT}:3000"

    env_file:
      - .env

    environment:
      PORT: ${APP_PORT}

      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

      NODE_ENV: production

    restart: unless-stopped
    init: true